In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('results.csv', index_col = 0)
data

,Profit,Expect_dur,Viol_prob_exact,Viol_prob_heur,Viol_prob_heur_std,taken_time
100,33.0,96.274,0.097,0.100,0.028,6.821
200,33.0,96.486,0.097,0.105,0.021,13.713
300,33.0,96.486,0.096,0.097,0.017,20.999
400,33.0,96.486,0.094,0.108,0.014,26.868
500,33.0,96.073,0.095,0.118,0.014,34.371
600,33.0,96.016,0.086,0.088,0.011,42.544
700,33.0,95.421,0.094,0.100,0.011,50.542
800,33.0,96.913,0.095,0.091,0.009,58.382
900,33.0,95.754,0.089,0.093,0.009,67.531
1000,33.0,96.081,0.094,0.094,0.009,74.367
expected,37.0,118.841,0.413,0.000,0.000,0.008